# Data Understanding

## 1. Objectives
---
The objective of data understanding is to gain insights into the data prior to data preparation and analysis, allowing us to identify its key characteristics and underlying data quality issues.

The assessment focuses on understanding:

- the structure and grain of the dataset,
- the meaning and analytical role of the available variables,
- the technical data types and value characteristics,
- potential data quality issues and inconsistencies, and
- the extent to which the available data can support the defined
  business questions.

The findings from this assessment will be used to determine the requirements and priorities for the Data Preparation stage.

## 2. Dataset Overview

### 2.1 Data Loading

Importing the Pandas library to explore dataset characteristics and perform initial data understanding prior to preparation.

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../data/raw/trendOne_raw.csv")

### 2.2 Data Dimensions

Check the dataset dimensions using `df.shape`

In [10]:
row_c, column_c = df.shape
print(f"Number of rows: {row_c}")
print(f"Number of rows: {column_c}")

Number of rows: 3900
Number of rows: 18

The dataset consists of 3,900 rows and 18 columns.

### 2.3 Initial inspection

Inspect the top, bottom, and random samples of the dataset using `head()`, `tail()`, and `sample(5)`.

In [14]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [15]:
df.tail()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [16]:
df.sample(5)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
771,772,22,Male,Sweater,Clothing,68,Hawaii,L,Cyan,Fall,2.6,Yes,Next Day Air,Yes,Yes,34,Bank Transfer,Fortnightly
3300,3301,26,Female,Hat,Accessories,80,Oklahoma,M,Charcoal,Spring,4.0,No,Express,No,No,40,Bank Transfer,Bi-Weekly
1580,1581,65,Male,Sneakers,Footwear,71,North Dakota,L,Cyan,Summer,3.7,No,Standard,Yes,Yes,30,Cash,Annually
916,917,49,Male,Jeans,Clothing,34,Illinois,S,Blue,Spring,2.7,Yes,Standard,Yes,Yes,16,Venmo,Monthly
2426,2427,70,Male,Jacket,Outerwear,42,Florida,M,Olive,Fall,4.6,No,Free Shipping,No,No,26,Debit Card,Every 3 Months

Initial observations show that dataset covering customer demographics, product details, shopping behavior, subscription status, and promo activity. 
A deeper breakdown of individual record representations will be conducted separately, as high-level visual inspection offers limited context.

List of column names

In [19]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases']

Based on the column names above, standardizing them to lowercase and snake_case (replacing spaces with underscores) will improve consistency. This renaming step will be carried out during the Data Preprocessing phase, following the initial Data Understanding.

## 3. Dataset Structure

### 3.1 Unit of observation / grain

The unit of observation describes what a single row in the dataset represents. Identifying the data grain is important because it
determines how customer counts, purchase values, and other metrics should be interpreted and aggregated.

The grain is assessed by examining the available identifiers and their uniqueness across the dataset.

Assuming customer_id serves as the primary identifier based on standard domain practices, we need to validate this assumption through further checks.

In [24]:
print(f"Number of rows in dataset           : {row_c}")
print(f"Number of unique `Custome ID` column: {df["Customer ID"].nunique()}")
print(f"Duplicate 'Customer ID'             : {df["Customer ID"].duplicated().sum()}")
print(f"Missing `Customer ID`               : {df["Customer ID"].isna().sum()}")
print(f"`Customer ID` unique (True/False)   : {df["Customer ID"].is_unique}")

Number of rows in dataset           : 3900
Number of unique `Custome ID` column: 3900
Duplicate 'Customer ID'             : 0
Missing `Customer ID`               : 0
`Customer ID` unique (True/False)   : True

As shown above, `Customer ID` is unique across all observations, with no missing or duplicate IDs.

Based on this, each row represents a distinct customer observation.

**Data grain: 1 row = 1 unique customer**

### 3.2 Variables Inventory

After establishing the data grain, the available variables are reviewed to understand what information is captured for each customer observation.

This provides an initial inventory of the dataset and helps determine whether the available fields can support the analytical requirements
defined earlier.

In [28]:
variable_inventory = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
})

variable_inventory

                    Column Data Type
0              Customer ID     int64
1                      Age     int64
2                   Gender       str
3           Item Purchased       str
4                 Category       str
5    Purchase Amount (USD)     int64
6                 Location       str
7                     Size       str
8                    Color       str
9                   Season       str
10           Review Rating   float64
11     Subscription Status       str
12           Shipping Type       str
13        Discount Applied       str
14         Promo Code Used       str
15      Previous Purchases     int64
16          Payment Method       str
17  Frequency of Purchases       str

The dataset contains 18 variables covering customer characteristics, product information, purchasing behavior, promotional activity,
subscription status, and purchase history. The available variables provide information across several analytical dimensions that will 
be assessed against the business questions in the later stages.

### 3.3 Identifiers & Cardinality

In [31]:
categorical_cols = df.select_dtypes(include=["object", "str"]).columns
cardinality = pd.DataFrame({
    "Column": categorical_cols,
    "Unique Values": [df[col].nunique() for col in categorical_cols]
})

cardinality

                    Column  Unique Values
0                   Gender              2
1           Item Purchased             25
2                 Category              4
3                 Location             50
4                     Size              4
5                    Color             25
6                   Season              4
7      Subscription Status              2
8            Shipping Type              6
9         Discount Applied              2
10         Promo Code Used              2
11          Payment Method              6
12  Frequency of Purchases              7

In [32]:
for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

Gender
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Item Purchased
<StringArray>
[    'Blouse',    'Sweater',      'Jeans',    'Sandals',   'Sneakers',
      'Shirt',     'Shorts',       'Coat',    'Handbag',      'Shoes',
      'Dress',      'Skirt', 'Sunglasses',      'Pants',     'Jacket',
     'Hoodie',    'Jewelry',    'T-shirt',      'Scarf',        'Hat',
      'Socks',   'Backpack',       'Belt',      'Boots',     'Gloves']
Length: 25, dtype: str

Category
<StringArray>
['Clothing', 'Footwear', 'Outerwear', 'Accessories']
Length: 4, dtype: str

Location
<StringArray>
[      'Kentucky',          'Maine',  'Massachusetts',   'Rhode Island',
         'Oregon',        'Wyoming',        'Montana',      'Louisiana',
  'West Virginia',       'Missouri',       'Arkansas',         'Hawaii',
       'Delaware',  'New Hampshire',       'New York',        'Alabama',
    'Mississippi', 'North Carolina',     'California',       'Oklahoma',
        'Florida',          'Texas',         'Nevada',         'Kansas',
       'Colorado',   'North Dakota',       'Illinois',        'Indiana',
        'Arizona',         'Alaska',      'Tennessee',           'Ohio',
     'New Jersey',       'Maryland',        'Vermont',     'New Mexico',
 'South Carolina',          'Idaho',   'Pennsylvania',    'Connecticut',
           'Utah',       'Virginia',        'Georgia',       'Nebraska',
           'Iowa',   'South Dakota',      'Minnesota',     'Washington',
      'Wisconsin',       'Michigan']
Length: 50, dtype: str

Size
<StringArray>
['L', 'S', 'M', 'XL']
Length: 4, dtype: str

Color
<StringArray>
[     'Gray',    'Maroon', 'Turquoise',     'White',  'Charcoal',    'Silver',
      'Pink',    'Purple',     'Olive',      'Gold',    'Violet',      'Teal',
  'Lavender',     'Black',     'Green',     'Peach',       'Red',      'Cyan',
     'Brown',     'Beige',    'Orange',    'Indigo',    'Yellow',   'Magenta',
      'Blue']
Length: 25, dtype: str

Season
<StringArray>
['Winter', 'Spring', 'Summer', 'Fall']
Length: 4, dtype: str

Subscription Status
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Shipping Type
<StringArray>
[       'Express',  'Free Shipping',   'Next Day Air',       'Standard',
 '2-Day Shipping',   'Store Pickup']
Length: 6, dtype: str

Discount Applied
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Promo Code Used
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Payment Method
<StringArray>
['Venmo', 'Cash', 'Credit Card', 'PayPal', 'Bank Transfer', 'Debit Card']
Length: 6, dtype: str

Frequency of Purchases
<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

The categorical variables show different levels of cardinality, depending on the type of information represented.

Variables such as `Gender`, `Subscription Status`, and `Discount Applied` have relatively low cardinality, while variables such as `Item Purchased`
and `Location` contain a larger number of distinct values.

The observed categories will be examined further for consistency and validity in the Data Quality Assessment.

## 4. Data Quality Assesment

### 4.1 Data types

The technical data types of the variables are reviewed to determine whether they are appropriate for their intended analytical roles.

The assessment distinguishes between the technical representation of a variable in the dataset and its analytical meaning.

In [37]:
dtype_assesment = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values
})

dtype_assesment

                    Column Data Type
0              Customer ID     int64
1                      Age     int64
2                   Gender       str
3           Item Purchased       str
4                 Category       str
5    Purchase Amount (USD)     int64
6                 Location       str
7                     Size       str
8                    Color       str
9                   Season       str
10           Review Rating   float64
11     Subscription Status       str
12           Shipping Type       str
13        Discount Applied       str
14         Promo Code Used       str
15      Previous Purchases     int64
16          Payment Method       str
17  Frequency of Purchases       str

The dataset contains integer, floating-point, and string variables.

The technical data types are generally consistent with the observed values. Identifier and categorical fields are interpreted according to
their analytical roles rather than their storage types.

No immediate data type issue was identified at this stage. Any required type conversion will be addressed during Data Preparation.

### 4.2 Missing values

The dataset is assessed for missing values across all variables.

This is important because missing observations may affect customer
counts, aggregations, statistical analysis, and downstream modeling or
segmentation.

In [41]:
missing = pd.DataFrame({
    "Missing Count": df.isna().sum(),
    "Missing %": df.isna().mean() * 100
})

missing[missing["Missing Count"] > 0]

               Missing Count  Missing %
Review Rating             37   0.948718

The review_rating feature has 37 missing entries (~0.95% of total records). Because missingness is under 1%, mean or median imputation is recommended to address these null values.

### 4.3 Duplicate & uniqueness

The dataset is checked for duplicate records and repeated identifier values.

Duplicate records may lead to double-counting and distort customer-level metrics. Identifier uniqueness is also reviewed to ensure that the
established data grain remains valid.

In [45]:
df.duplicated().sum()

np.int64(0)

No exact duplicate rows were identified in the dataset.

### 4.4 Categorical values

Categorical variables are reviewed to identify inconsistent, unexpected,
or potentially invalid category values.

This assessment focuses on the values present in the raw data without
modifying them. Any required standardization will be handled during
Data Preparation.

In [49]:
for col in categorical_cols:
    print(f"\n{col}: {df[col].nunique()} unique values")
    print(df[col].unique())

Gender: 2 unique values
<StringArray>
['Male', 'Female']
Length: 2, dtype: str

Item Purchased: 25 unique values
<StringArray>
[    'Blouse',    'Sweater',      'Jeans',    'Sandals',   'Sneakers',
      'Shirt',     'Shorts',       'Coat',    'Handbag',      'Shoes',
      'Dress',      'Skirt', 'Sunglasses',      'Pants',     'Jacket',
     'Hoodie',    'Jewelry',    'T-shirt',      'Scarf',        'Hat',
      'Socks',   'Backpack',       'Belt',      'Boots',     'Gloves']
Length: 25, dtype: str

Category: 4 unique values
<StringArray>
['Clothing', 'Footwear', 'Outerwear', 'Accessories']
Length: 4, dtype: str

Location: 50 unique values
<StringArray>
[      'Kentucky',          'Maine',  'Massachusetts',   'Rhode Island',
         'Oregon',        'Wyoming',        'Montana',      'Louisiana',
  'West Virginia',       'Missouri',       'Arkansas',         'Hawaii',
       'Delaware',  'New Hampshire',       'New York',        'Alabama',
    'Mississippi', 'North Carolina',     'California',       'Oklahoma',
        'Florida',          'Texas',         'Nevada',         'Kansas',
       'Colorado',   'North Dakota',       'Illinois',        'Indiana',
        'Arizona',         'Alaska',      'Tennessee',           'Ohio',
     'New Jersey',       'Maryland',        'Vermont',     'New Mexico',
 'South Carolina',          'Idaho',   'Pennsylvania',    'Connecticut',
           'Utah',       'Virginia',        'Georgia',       'Nebraska',
           'Iowa',   'South Dakota',      'Minnesota',     'Washington',
      'Wisconsin',       'Michigan']
Length: 50, dtype: str

Size: 4 unique values
<StringArray>
['L', 'S', 'M', 'XL']
Length: 4, dtype: str

Color: 25 unique values
<StringArray>
[     'Gray',    'Maroon', 'Turquoise',     'White',  'Charcoal',    'Silver',
      'Pink',    'Purple',     'Olive',      'Gold',    'Violet',      'Teal',
  'Lavender',     'Black',     'Green',     'Peach',       'Red',      'Cyan',
     'Brown',     'Beige',    'Orange',    'Indigo',    'Yellow',   'Magenta',
      'Blue']
Length: 25, dtype: str

Season: 4 unique values
<StringArray>
['Winter', 'Spring', 'Summer', 'Fall']
Length: 4, dtype: str

Subscription Status: 2 unique values
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Shipping Type: 6 unique values
<StringArray>
[       'Express',  'Free Shipping',   'Next Day Air',       'Standard',
 '2-Day Shipping',   'Store Pickup']
Length: 6, dtype: str

Discount Applied: 2 unique values
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Promo Code Used: 2 unique values
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

Payment Method: 6 unique values
<StringArray>
['Venmo', 'Cash', 'Credit Card', 'PayPal', 'Bank Transfer', 'Debit Card']
Length: 6, dtype: str

Frequency of Purchases: 7 unique values
<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

The categorical variables were reviewed for inconsistent or unexpected values. The observed categories are generally consistent within their
respective fields.

No immediate categorical-value issue requiring correction was identified.

## 5. Value & Range Assesment

### 5.1 Numerical Variables

The distribution of numerical variables is reviewed to understand their basic range, central tendency, and variability.

This assessment provides an initial view of the numerical data and helps
identify values that may require further investigation during data
preparation or exploratory analysis.

In [54]:
numerical_cols = df.select_dtypes(include=["int64", "float64"]).columns

df[numerical_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0

Initial observation shows no obvious anomalies. The data appears expected and follows a normal distribution.

### 5.2 Categorical Variables

The frequency distribution of categorical variables is reviewed to understand how observations are distributed across the available
categories.

This provides an initial view of category representation and helps identify potentially unusual or highly imbalanced values for further
consideration.

In [58]:
for no, col in enumerate(categorical_cols):
    print(f"{no}. {col}:")
    cat_var_col = pd.DataFrame({
            "Count": df[col].value_counts(dropna=False),
            "Percentage": df[col].value_counts(normalize=True, dropna=False) * 100
        })
    display(cat_var_col)

0. Gender:

        Count  Percentage
Gender
Male     2652        68.0
Female   1248        32.0

1. Item Purchased:

                Count  Percentage
Item Purchased
Blouse            171    4.384615
Pants             171    4.384615
Jewelry           171    4.384615
Shirt             169    4.333333
Dress             166    4.256410
Sweater           164    4.205128
Jacket            163    4.179487
Coat              161    4.128205
Sunglasses        161    4.128205
Belt              161    4.128205
Sandals           160    4.102564
Socks             159    4.076923
Skirt             158    4.051282
Shorts            157    4.025641
Scarf             157    4.025641
Hat               154    3.948718
Handbag           153    3.923077
Hoodie            151    3.871795
Shoes             150    3.846154
T-shirt           147    3.769231
Sneakers          145    3.717949
Boots             144    3.692308
Backpack          143    3.666667
Gloves            140    3.589744
Jeans             124    3.179487

2. Category:

             Count  Percentage
Category
Clothing      1737   44.538462
Accessories   1240   31.794872
Footwear       599   15.358974
Outerwear      324    8.307692

3. Location:

                Count  Percentage
Location
Montana            96    2.461538
California         95    2.435897
Idaho              93    2.384615
Illinois           92    2.358974
Alabama            89    2.282051
Minnesota          88    2.256410
New York           87    2.230769
Nevada             87    2.230769
Nebraska           87    2.230769
Delaware           86    2.205128
Maryland           86    2.205128
Vermont            85    2.179487
Louisiana          84    2.153846
North Dakota       83    2.128205
West Virginia      81    2.076923
Missouri           81    2.076923
New Mexico         81    2.076923
Mississippi        80    2.051282
Kentucky           79    2.025641
Arkansas           79    2.025641
Indiana            79    2.025641
Georgia            79    2.025641
North Carolina     78    2.000000
Connecticut        78    2.000000
Maine              77    1.974359
Texas              77    1.974359
Tennessee          77    1.974359
Ohio               77    1.974359
Virginia           77    1.974359
South Carolina     76    1.948718
Oklahoma           75    1.923077
Colorado           75    1.923077
Wisconsin          75    1.923077
Oregon             74    1.897436
Pennsylvania       74    1.897436
Washington         73    1.871795
Michigan           73    1.871795
Massachusetts      72    1.846154
Alaska             72    1.846154
Wyoming            71    1.820513
New Hampshire      71    1.820513
Utah               71    1.820513
South Dakota       70    1.794872
Iowa               69    1.769231
Florida            68    1.743590
New Jersey         67    1.717949
Hawaii             65    1.666667
Arizona            65    1.666667
Rhode Island       63    1.615385
Kansas             63    1.615385

4. Size:

      Count  Percentage
Size
M      1755        45.0
L      1053        27.0
S       663        17.0
XL      429        11.0

5. Color:

           Count  Percentage
Color
Olive        177    4.538462
Yellow       174    4.461538
Silver       173    4.435897
Teal         172    4.410256
Green        169    4.333333
Black        167    4.282051
Violet       166    4.256410
Cyan         166    4.256410
Gray         159    4.076923
Maroon       158    4.051282
Orange       154    3.948718
Charcoal     153    3.923077
Pink         153    3.923077
Magenta      152    3.897436
Blue         152    3.897436
Purple       151    3.871795
Peach        149    3.820513
Red          148    3.794872
Lavender     147    3.769231
Beige        147    3.769231
Indigo       147    3.769231
Turquoise    145    3.717949
White        142    3.641026
Brown        141    3.615385
Gold         138    3.538462

6. Season:

        Count  Percentage
Season
Spring    999   25.615385
Fall      975   25.000000
Winter    971   24.897436
Summer    955   24.487179

7. Subscription Status:

                     Count  Percentage
Subscription Status
No                    2847        73.0
Yes                   1053        27.0

8. Shipping Type:

                Count  Percentage
Shipping Type
Free Shipping     675   17.307692
Standard          654   16.769231
Store Pickup      650   16.666667
Next Day Air      648   16.615385
Express           646   16.564103
2-Day Shipping    627   16.076923

9. Discount Applied:

                  Count  Percentage
Discount Applied
No                 2223        57.0
Yes                1677        43.0

10. Promo Code Used:

                 Count  Percentage
Promo Code Used
No                2223        57.0
Yes               1677        43.0

11. Payment Method:

                Count  Percentage
Payment Method
PayPal            677   17.358974
Credit Card       671   17.205128
Cash              670   17.179487
Debit Card        636   16.307692
Venmo             634   16.256410
Bank Transfer     612   15.692308

12. Frequency of Purchases:

                        Count  Percentage
Frequency of Purchases
Every 3 Months            584   14.974359
Annually                  572   14.666667
Quarterly                 563   14.435897
Monthly                   553   14.179487
Bi-Weekly                 547   14.025641
Fortnightly               542   13.897436
Weekly                    539   13.820513

The categorical distributions show varying levels of representation across groups. Some variables contain relatively balanced categories,
while others are more concentrated in a smaller number of groups.

These distributions will be considered when interpreting comparisons between customer groups in the EDA and statistical analysis stages.

### 5.3 Range & Possibilities Check

Numerical and categorical values are reviewed against their expected business meaning and plausible ranges.

The purpose is to identify values that are technically valid from a data-type perspective but may be inconsistent with the intended meaning
of the variable.

In [88]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Customer ID,3900.0,1950.500000,1125.977353,1.0,975.75,1950.5,2925.25,3900.0
Age,3900.0,44.068462,15.207589,18.0,31.00,44.0,57.00,70.0
Purchase Amount (USD),3900.0,59.764359,23.685392,20.0,39.00,60.0,81.00,100.0
Review Rating,3863.0,3.750065,0.716983,2.5,3.10,3.8,4.40,5.0
Previous Purchases,3900.0,25.351538,14.447125,1.0,13.00,25.0,38.00,50.0

In [132]:
range_check = {
    "Age": df["Age"] < 0,
    "Purchase Amount (USD)": df["Purchase Amount (USD)"] < 0,
    "Review Rating": (df["Review Rating"] < 0) | (df["Review Rating"] > 5)
}

for rc_k, rc_v in range_check.items():
    if not rc_v.any():
        print(f"{rc_k}: No problem")
    else:
        print(f"{rc_k}: Problem found")

Age: No problem
Purchase Amount (USD): No problem
Review Rating: No problem

Based on the above, no issues were identified as all values fall within normal ranges, with no outliers or suspicious data points observed.

### 5.4 Potential Outliers

Potential outliers are assessed to identify observations that are unusually distant from the rest of the distribution.

An outlier is not automatically treated as an error. Any potential outlier identified at this stage is flagged for further investigation
rather than removed or modified.

In [149]:
def iqr_outlier_summary(df, columns):
    results = []

    for col in columns:
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1

        lower = q1 - 1.5 * iqr
        upper = q3 + 1.5 * iqr

        outliers = ((df[col] < lower) | (df[col] > upper)).sum()

        results.append({
            "Column": col,
            "Q1": q1,
            "Q3": q3,
            "IQR": iqr,
            "Lower Bound": lower,
            "Upper Bound": upper,
            "Potential Outliers": outliers
        })

    return pd.DataFrame(results)

iqr_outlier_summary(df, numerical_cols)

,Column,Q1,Q3,IQR,Lower Bound,Upper Bound,Potential Outliers
0,Customer ID,975.75,2925.25,1949.5,-1948.50,5849.50,0
1,Age,31.00,57.00,26.0,-8.00,96.00,0
2,Purchase Amount (USD),39.00,81.00,42.0,-24.00,144.00,0
3,Review Rating,3.10,4.40,1.3,1.15,6.35,0
4,Previous Purchases,13.00,38.00,25.0,-24.50,75.50,0

As outlined in the rough overview in section 5.3, it has been verified that the dataset contains no extreme outliers across 
its numerical columns.

### 5.5 Cross-Variable Consistency

I considered cross-variable consistency checks, but the available dataset did not provide sufficient business rules to define which combinations should be considered invalid. I therefore avoided making assumptions about business logic that was not supported by the data.

## 6. Business Question Feasibility

| Business Question                                                             | Feasibility                          | Available Evidence                                                       | Description                                                                                                                                     | 
| ----------------------------------------------------------------------------- | ------------------------------------ | ------------------------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------- |
| Q1. Which customer characteristics are associated with higher purchase value? | Feasible                             | Customer characteristics and `Purchase Amount (USD)` available           |                                                                                                                                                |
| Q2. How does purchase value vary across customer groups?                      | Feasible                             | Demographic, behavioral, product and purchase variables available        |                                                                                                                                                |
| Q3. How effectively does TrendOne retain customers over time?                 | Not feasible                         | `Previous Purchases`, `Frequency of Purchases` available                 | The transaction dates or timestamps are missing, making time based retention or cohort analysis impossible as temporal data is a fundamental requirement. |
| Q4. Do purchasing behaviors differ across product categories?                 | Feasible                             | `Category`, `Purchase Amount`, `Previous Purchases`, `Frequency`         |                                                                                                                                                |
| Q5. Is discount usage associated with different purchasing behavior?          | Feasible                             | `Discount Applied`, `Purchase Amount`, `Previous Purchases`, `Frequency` |                                                                                                                                                |
| Q6. Is subscription status associated with purchasing behavior?               | Feasible                             | `Subscription Status`, purchase-related variables                        |                                                                                                                                                |
| Q7. Is subscription status associated with discount usage?                    | Feasible                             | `Subscription Status`, `Discount Applied`                                |                                                                                                                                                |

## 7. Summary & Next Steps

The data assessment established the structure, quality, and analytical limitations of the raw dataset.

The dataset contains 3,900 customer-level observations, with `Customer ID` serving as a unique identifier for each observation. The available
variables cover customer characteristics, purchasing behavior, product information, promotional activity, subscription status, and purchase
history.

During the data understanding and assessment phase, the dataset revealed no critical structural issues and can be considered exceptionally clean. However, time-based analyses such as retention and cohort tracking cannot be performed due to the complete absence of transaction dates or timestamps, which are fundamental prerequisites for temporal modeling.

The findings from this assessment will guide the Data Preparation stage, where the identified data requirements and analytical considerations
will be translated into the required transformations and validation steps.

## Next Steps

The next stage will focus on preparing the dataset for analysis,
including:

- Addressing any data quality issues identified during the assessment such as lowercase column name and snake case.
- Applying required data type or value transformations.
- Creating analytical features where necessary, such as adding a region column to group specific locations simplifies the data and provides broader analytical insights.
- Validating the prepared dataset.
- producing the analytical dataset required for EDA and subsequent.
  statistical analysis.